# Generated by Django 3.0.2 on 2020-02-27 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200226_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_inquir',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person_inquir',
            name='australia',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='person_inquir',
            name='canada',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='person_inquir',
            name='united_kingdom',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='person_inquir',
            name='usa',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
